"""AI analyst report (Feature: LLM-generated report).

Builds a human-readable investment summary from the forecast + technical +
sentiment data. When an OpenAI/Anthropic API key is configured the report is
generated by the LLM; otherwise a deterministic rule-based summary is produced
so the feature always renders.
"""
from __future__ import annotations

import logging
from typing import Any, Dict, Optional

logger = logging.getLogger("stockpredictor.services.llm_report")


def _model_client():
    """Return a configured LLM client (OpenAI or Anthropic) or None."""
    import os

    openai_key = os.getenv("OPENAI_API_KEY")
    anthropic_key = os.getenv("ANTHROPIC_API_KEY")
    if openai_key:
        try:
            from openai import OpenAI

            return {"provider": "openai", "client": OpenAI(api_key=openai_key)}
        except Exception as exc:  # pragma: no cover - env dependent
            logger.warning("OpenAI client unavailable: %s", exc)
    if anthropic_key:
        try:
            from anthropic import Anthropic

            return {"provider": "anthropic", "client": Anthropic(api_key=anthropic_key)}
        except Exception as exc:  # pragma: no cover - env dependent
            logger.warning("Anthropic client unavailable: %s", exc)
    return None


def _call_llm(client: Dict[str, Any], prompt: str) -> Optional[str]:
    provider = client["provider"]
    client_obj = client["client"]
    try:
        if provider == "openai":
            response = client_obj.chat.completions.create(
                model="gpt-4o-mini",
                messages=[
                    {"role": "system", "content": "You are a cautious, data-driven stock analyst. Answer concisely with bullet points."},
                    {"role": "user", "content": prompt},
                ],
                max_tokens=500,
                temperature=0.4,
            )
            return response.choices[0].message.content
        if provider == "anthropic":
            response = client_obj.messages.create(
                model="claude-3-5-haiku-latest",
                max_tokens=500,
                system="You are a cautious, data-driven stock analyst. Answer concisely with bullet points.",
                messages=[{"role": "user", "content": prompt}],
            )
            parts = [block.text for block in response.content if getattr(block, "type", "") == "text"]
            return "\n".join(parts) if parts else None
    except Exception as exc:  # pragma: no cover - API failures
        logger.warning("LLM call failed (%s): %s", provider, exc)
    return None


def rule_based_summary(
    symbol: str,
    forecast: Dict[str, Any],
    technical: Dict[str, Any],
    sentiment: Optional[Dict[str, Any]] = None,
) -> str:
    """Deterministic summary used when no LLM is configured/available."""
    lines: list = [f"Summary for {symbol}"]
    current = _num(forecast, "current_price")
    last = _num(forecast, "last_close")
    if current or last:
        lines.append(f"Last close was ${last or current:.2f}.")
    predicted = _num(forecast, "predicted_price")
    if predicted:
        change = (predicted / current - 1) * 100 if current else 0.0
        direction = "up" if change >= 0 else "down"
        lines.append(f"The {forecast.get('days', 30)}-day forecast points {direction} "
                     f"{abs(change):.1f}% to ~${predicted:.2f}.")

    confidence = _num(forecast, "confidence")
    if confidence:
        lines.append(f"Model confidence is {confidence * 100:.0f}%.")

    rating = technical.get("overall_rating") or technical.get("rating")
    if rating:
        lines.append(f"Technical indicators score the stock {rating}.")
    trend = technical.get("trend") or technical.get("market_trend")
    if trend:
        lines.append(f"Observed trend: {trend}.")

    if sentiment:
        polarity = _num(sentiment, "polarity")
        count = sentiment.get("total") or sentiment.get("count") or 0
        if polarity is not None:
            mood = "positive" if polarity > 0.05 else ("negative" if polarity < -0.05 else "neutral")
            lines.append(f"News/social sentiment is {mood} (score {polarity:.2f}) across {count} articles.")
    lines.append("This is not financial advice — treat any figure as an estimate.")
    return "\n".join(lines)


def _num(d: Optional[Dict[str, Any]], key: str) -> Optional[float]:
    if not d:
        return None
    value = d.get(key)
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def generate_analyst_report(
    symbol: str,
    forecast: Dict[str, Any],
    technical: Dict[str, Any],
    sentiment: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """Generate an analyst report, preferring an LLM when configured."""
    prompt_lines = [
        f"Analyze {symbol}. Price data: {forecast}.",
        f"Technicals: {technical}.",
        f"Sentiment: {sentiment}.",
        "Give a short risk-aware outlook with 3-5 bullet points.",
    ]
    prompt = "\n".join(prompt_lines)
    client = _model_client()
    provider = None
    text = None
    if client is not None:
        text = _call_llm(client, prompt)
        provider = client["provider"]
    if not text:
        text = rule_based_summary(symbol, forecast, technical, sentiment)
        provider = "rule_based"
    return {
        "success": True,
        "symbol": symbol,
        "provider": provider,
        "report": text,
    }
