"""initial state schema

Revision ID: 4aafae91ad60
Revises: 
Create Date: 2026-08-11 10:37:44.569095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4aafae91ad60'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('condition', sa.String(length=8), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('created', sa.String(length=64), nullable=False),
    sa.Column('last_triggered', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('row_id'),
    sa.UniqueConstraint('email', 'alert_id', name='uq_alert_email_id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_email'), ['email'], unique=False)

    op.create_table('analysis_history',
    sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('row_id')
    )
    with op.batch_alter_table('analysis_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_history_email'), ['email'], unique=False)

    op.create_table('meta',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('password_reset_tokens',
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('expires', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_email'), ['email'], unique=False)

    op.create_table('pending_registrations',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('otp', sa.String(length=8), nullable=False),
    sa.Column('expires', sa.String(length=64), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('portfolios',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('positions', sa.Text(), nullable=False),
    sa.Column('history', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('prediction_cache',
    sa.Column('key', sa.String(length=1024), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('last_login', sa.String(length=64), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('password_changed', sa.String(length=64), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('watchlist_entries',
    sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('row_id'),
    sa.UniqueConstraint('email', 'symbol', name='uq_watchlist_email_symbol')
    )
    with op.batch_alter_table('watchlist_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_entries_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_entries_email'))

    op.drop_table('watchlist_entries')
    op.drop_table('users')
    op.drop_table('prediction_cache')
    op.drop_table('portfolios')
    op.drop_table('pending_registrations')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_email'))

    op.drop_table('password_reset_tokens')
    op.drop_table('meta')
    with op.batch_alter_table('analysis_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_history_email'))

    op.drop_table('analysis_history')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_email'))

    op.drop_table('alerts')
    # ### end Alembic commands ###
